---
title: "R-part-assignment-1"
author: "Dans Lismanis"
date: "2023-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1)List of all the commands i ran
```{r}
x <- c(1,2,3,4)
x
x=c(1,6,2)
y=c(1,4,3)
length(x)
length(y)
x+y
ls()
rm(x,y)
ls()
rm(list=ls())
x=matrix(data = c(1,2,3,4),nrow = 2,ncol = 2)
x
matrix(data = c(1,2,3,4),nrow = 2,ncol = 2,byrow = TRUE)
sqrt(x)
x^2
x= rnorm(50)
y=x+rnorm(50, mean=50, sd=0.1)
cor(x,y)
set.seed(1303)
rnorm(50)
set.seed(3)
y=rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
##End of 2.3.1
x=rnorm(100)
y=rnorm(100)
plot(x,y)
plot(x,y,xlab="Label for x axis", main="this is a scatter plot")
pdf("Figure.pdf")
plot(x,y, col="green")
dev.off()
x=seq(1,10)
x=1:10
x=seq(-pi,pi,length=50)
y=x
f=outer(x,y, function(x,y) cos(y)/(1+x^2))
contour(x,y,f)
contour(x,y,f,nlevels = 45,add=T)
fa=(f-t(f))/2
contour(x,y,fa,nlevels = 45)
image(x,y,fa)
persp(x,y,fa,theta=30,phi = 40)
A=matrix(1:16,4,4)
A[2,3]
A[c(1,3),c(2,4)]
A[1:3,2:4]
A[1:2,]
A[,1:2]
A[1,]
A[-c(1,3),]
A[-c(1,3), -c(1,3,4)]
dim(A)
Auto=read.table("Auto.data",header=T,na.strings = "?",stringsAsFactors = T)
View(Auto)
head(Auto)
Auto=read.csv("Auto.csv",na.strings = "?",stringsAsFactors = T)
View(Auto)
dim(Auto)
Auto[1:4,]
Auto=na.omit(Auto)
names(Auto)
plot(Auto$cylinders,Auto$mpg)
attach(Auto)
plot(cylinders,mpg, col='red', varwidth=T, xlab="cylinders", ylab="mpg")
cylinders=as.factor(cylinders)
hist(mpg,col=2,breaks=15)
pairs(Auto)
pairs(~mpg+displacement+horsepower+weight+acceleration,data=Auto)
plot(horsepower,mpg)
identify(horsepower,mpg,name)
summary(Auto)
summary(mpg)
```

### 2)One plot explained
```{r}
hist(mpg,col=2,breaks=15)
```

Here a histogram is provided showing all the fuel consumptions in miles per gallon of different cars.